import {
	MdOutlineAccountBalanceWallet,
	MdOutlineApartment,
	MdOutlineArticle,
	MdOutlineBusiness,
	MdOutlineChecklist,
	MdOutlineDescription,
	MdOutlineEvent,
	MdOutlineFactCheck,
	MdOutlineForwardToInbox,
	MdOutlineGpsFixed,
	MdOutlineGroup,
	MdOutlineInventory2,
	MdOutlineInsights,
	MdOutlineMail,
	MdOutlinePerson,
	MdOutlineSell,
	MdOutlineShield,
	MdOutlineTask,
	MdOutlineTune,
	MdOutlineViewKanban,
	MdOutlineCreditCard,
	MdOutlineBadge,
	MdOutlineDashboard,
	MdOutlineForum,
	MdOutlineContacts,
	MdOutlineBusinessCenter,
	MdOutlineEventNote,
	MdOutlineBarChart,
	MdOutlineHowToReg,
} from "react-icons/md";

export const SIDEBAR_NAV_ITEMS = [
	{ to: "/dashboard", label: "Dashboard", icon: MdOutlineDashboard, end: true },
	{ to: "/communications", label: "Inbox", icon: MdOutlineMail },
	{ to: "/leads", label: "Leads", icon: MdOutlineBadge },
	{ to: "/contacts", label: "Contacts", icon: MdOutlineContacts },
	{ to: "/accounts", label: "Accounts", icon: MdOutlineBusinessCenter },
	{ to: "/deals", label: "Pipeline", icon: MdOutlineAccountBalanceWallet },
	{
		to: "/events",
		label: "Event Projects",
		icon: MdOutlineEvent,
		module: "events",
	},
	{ to: "/reports", label: "Team Reports", icon: MdOutlineInsights },
	{
		to: "/analytics",
		label: "Analytics",
		icon: MdOutlineBarChart,
		permission: "reports.view.org",
	},
	{
		to: "/invoices",
		label: "Invoices",
		icon: MdOutlineArticle,
		module: "invoices",
	},
	{ to: "/tasks", label: "Tasks", icon: MdOutlineChecklist },
	{ to: "/settings", label: "Settings", icon: MdOutlineTune },
];

export const SUPER_ADMIN_NAV_ITEMS = [
	{
		to: "/platform",
		label: "Organizations",
		icon: MdOutlineApartment,
		end: true,
	},
];

export const SETTINGS_TABS = [
	{
		to: "/settings/customization",
		label: "Customization Studio",
		desc: "Modules and setup overview.",
		icon: MdOutlineTune,
		permission: "teams.view",
	},
	{
		to: "/settings/company-profile",
		label: "Company Profile",
		desc: "Logo, name, tagline, address.",
		icon: MdOutlineBusiness,
		permission: "teams.view",
	},
	{
		to: "/settings/my-account",
		label: "My Account",
		desc: "Connect your own Google account for sending email.",
		icon: MdOutlinePerson,
		permission: "teams.view",
	},
	{
		to: "/settings/document-templates",
		label: "Document Templates",
		desc: "Invoice footer note and .docx mail-merge templates.",
		icon: MdOutlineArticle,
		permission: "teams.view",
	},
	{
		to: "/settings/custom-fields",
		label: "Custom Fields",
		desc: "Define company-specific properties for CRM records.",
		icon: MdOutlineDescription,
		permission: "teams.view",
	},
	{
		to: "/settings/lead-scoring",
		label: "Lead Scoring",
		desc: "Auto-prioritize leads with custom scoring rules.",
		icon: MdOutlineGpsFixed,
		permission: "leadScoring.view",
		module: "leadScoring",
	},
	{
		to: "/settings/automations",
		label: "Automations",
		desc: "Auto-assign, prioritize, or follow up on new leads/deals.",
		icon: MdOutlineChecklist,
		permission: "org.settings.manage",
	},
	{
		to: "/settings/email-templates",
		label: "Email Templates",
		desc: "Reusable templates for Inbox, Invoices, and Event follow-ups.",
		icon: MdOutlineForwardToInbox,
		permission: "org.settings.manage",
	},
	{
		to: "/settings/task-boards",
		label: "Task Boards",
		desc: "Statuses, milestones and labels for the task tracker.",
		icon: MdOutlineViewKanban,
		permission: "taskBoards.view",
		module: "taskBoard",
	},
	{
		to: "/settings/client-types",
		label: "Client Types",
		desc: "Categorize clients by segment (e.g. Enterprise, SMB).",
		icon: MdOutlineSell,
		permission: "clientTypes.view",
	},
	{
		to: "/settings/products",
		label: "Products Catalog",
		desc: "Configure your service offerings and catalog pricing.",
		icon: MdOutlineInventory2,
		permission: "products.view",
	},
	{
		to: "/settings/events",
		label: "Events Manager",
		desc: "Track marketing expos, events, and trade shows.",
		icon: MdOutlineEvent,
		permission: "events.view",
		module: "events",
	},
	{
		to: "/settings/team",
		label: "Team Management",
		desc: "Manage team members, departments, and access roles.",
		icon: MdOutlineGroup,
		permission: "teams.view",
	},
	{
		to: "/settings/onboarding-email",
		label: "Onboarding Email",
		desc: "Customize the welcome email new teammates receive.",
		icon: MdOutlineHowToReg,
		permission: "org.settings.manage",
	},
	{
		to: "/settings/plans",
		label: "Plans & Billing",
		desc: "Manage subscription plans and active features limit.",
		icon: MdOutlineCreditCard,
		permission: "org.settings.manage",
	},
	{
		to: "/settings/audit-log",
		label: "System Audit Log",
		desc: "Track organizational activities and access audits.",
		icon: MdOutlineFactCheck,
		permission: "org.settings.manage",
	},
];

export const MODULE_ROUTE_GATES = {
	"/invoices": "invoices",
	"/events": "events",
	"/settings/lead-scoring": "leadScoring",
	"/settings/task-boards": "taskBoard",
};
